# Generated by Django 4.1.7 on 2023-02-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
