# Generated by Django 4.1 on 2023-01-02 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_account_author_account_meta_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="author",
            new_name="meta_author",
        ),
    ]
