# Generated by Django 4.1 on 2023-01-02 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_rename_author_account_meta_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="quote",
        ),
    ]
